# Generated by Django 6.0.5 on 2026-06-20 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sprints", "0004_sprint_data_import"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sprintdataimport",
            options={
                "ordering": ["-version_number"],
                "permissions": [
                    ("import_forecast", "Can upload forecast data for a sprint team"),
                    ("import_actuals", "Can upload actuals data for a sprint team"),
                ],
            },
        ),
    ]
