# Generated by Django 6.0.5 on 2026-06-21 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_project_sprint_started_in_sprint_completed_in"),
        ("recharges", "0002_alter_projecttypemapping_options"),
        ("sprints", "0007_sprintdataimportrow"),
        ("users", "0011_add_groupprofile_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprintdataimportrow",
            name="assignee_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprint_import_rows_as_assignee",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="sprintdataimportrow",
            name="label_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprint_import_rows",
                to="projects.projectlabel",
            ),
        ),
        migrations.AddField(
            model_name="sprintdataimportrow",
            name="mapping_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprint_import_rows",
                to="recharges.rechargetype",
            ),
        ),
    ]
