# Generated by Django 6.0.5 on 2026-06-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sprints", "0014_sprint_data_import_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprintdataimportreview",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sprintdataimportreviewresult",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
