# Generated by Django 6.0.5 on 2026-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sprints", "0018_add_confirm_forecast_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprintdataimportreviewresult",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("CHECK_ASSIGNEE", "Assignee"),
                    ("CHECK_SPRINT", "Sprint"),
                    ("CHECK_LABEL", "Label"),
                    ("CHECK_MAPPING", "Mapping"),
                    ("CHECK_CAPACITY", "Capacity"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
