# Generated by Django 6.0.5 on 2026-06-02 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="audit",
            new_name="audit_audit_module_7ca1b2_idx",
            old_name="audit_audit_module_resource_type_idx",
        ),
        migrations.RenameIndex(
            model_name="audit",
            new_name="audit_audit_module_131654_idx",
            old_name="audit_audit_module_action_idx",
        ),
    ]
