# Generated by Django 6.0.5 on 2026-06-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_remove_audit_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("activate", "Activate"),
                    ("deactivate", "Deactivate"),
                    ("set_default", "Set Default"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
