# Generated by Django 6.0.5 on 2026-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_alter_audit_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("activate", "Activate"),
                    ("deactivate", "Deactivate"),
                    ("set_default", "Set Default"),
                    ("restore", "Restore"),
                    ("lock", "Lock"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
