# Generated by Django 6.0.5 on 2026-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("codename", models.CharField(db_index=True, max_length=100)),
                ("label", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="categories", to="auth.permission"
                    ),
                ),
            ],
            options={
                "ordering": ["module", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module", "codename"),
                        name="permissions_permissioncategory_module_codename_uniq",
                    )
                ],
            },
        ),
    ]
