# Generated by Django 6.0.5 on 2026-06-01 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("permissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupPermissionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(0, "None"), (1, "Self"), (2, "Team"), (3, "All")],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_assignments",
                        to="permissions.permissioncategory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_categories",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "category"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "category"),
                        name="permissions_grouppermissioncategory_group_category_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPermissionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(0, "None"), (1, "Self"), (2, "Team"), (3, "All")],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="permissions.permissioncategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "category"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category"),
                        name="permissions_userpermissioncategory_user_category_uniq",
                    )
                ],
            },
        ),
    ]
