"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from pycore import DotEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env before any module that reads os.environ at import time
# (e.g. config.logging).
DotEnv(BASE_DIR).load_environ()

from config import database, logging  # noqa: E402

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n@t4zu#yq!@jwml0)x1rtn87rnnpo_z@_mg6=$$tgsy-ry!h$k"  # nosec B105  # noqa: E501

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# AppConfig.ready() will append the BASE_URL host after DB is available
ALLOWED_HOSTS: list[str] = ["localhost", "127.0.0.1", "[::1]"]

# Injected by scripts/dev/dev.py at runserver time for LAN access
_dev_lan_ip = os.environ.get("DEV_LAN_IP", "").strip()
if _dev_lan_ip and _dev_lan_ip not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_dev_lan_ip)

# COOP is only honoured by browsers on HTTPS (secure) origins.
# Sending it over plain HTTP causes a browser console warning and is ignored.
# Production deployments run HTTPS, so the header is restored there.
SECURE_CROSS_ORIGIN_OPENER_POLICY = None if DEBUG else "same-origin"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "apps.setup.apps.SetupConfig",
    "apps.configurations.apps.ConfigurationConfig",
    "apps.auth.apps.AuthConfig",
    "apps.oauth.apps.OAuthConfig",
    "apps.saml.apps.SAMLConfig",
    "apps.users.apps.UserConfig",
    "apps.permissions.apps.PermissionConfig",
    "apps.meta.apps.MetaConfig",
    "apps.dashboard.apps.DashboardConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.setup.middleware.SetupMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database — see config/database.py for engine selection and connection details.
DATABASES = database.DATABASES


AUTHENTICATION_BACKENDS = [
    "apps.permissions.backends.PermissionCategoryBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = "/static/"

# Media files (user uploads, avatars, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGGING = logging.LOGGING

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.auth.authentication.BearerTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
