"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from pycore import DotEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env before any module that reads os.environ at import time
# (e.g. config.logging).
DotEnv(BASE_DIR).load_environ()

from config import database, logging  # noqa: E402

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n@t4zu#yq!@jwml0)x1rtn87rnnpo_z@_mg6=$$tgsy-ry!h$k"  # nosec B105  # noqa: E501

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

# AppConfig.ready() will append the BASE_URL host after DB is available
ALLOWED_HOSTS: list[str] = ["*"] if DEBUG else ["localhost", "127.0.0.1", "[::1]"]

# Injected by scripts/dev/dev.py at runserver time for LAN access
_dev_lan_ip = os.environ.get("DEV_LAN_IP", "").strip()
if _dev_lan_ip and _dev_lan_ip not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_dev_lan_ip)

# COOP is only honoured by browsers on HTTPS (secure) origins.
# Sending it over plain HTTP causes a browser console warning and is ignored.
# Production deployments run HTTPS, so the header is restored there.
SECURE_CROSS_ORIGIN_OPENER_POLICY = None if DEBUG else "same-origin"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "apps.core.apps.CoreConfig",
    "apps.setup.apps.SetupConfig",
    "apps.configurations.apps.ConfigurationConfig",
    "apps.auth.apps.AuthConfig",
    "apps.oauth.apps.OAuthConfig",
    "apps.saml.apps.SAMLConfig",
    "apps.users.apps.UserConfig",
    "apps.permissions.apps.PermissionConfig",
    "apps.meta.apps.MetaConfig",
    "apps.audit.apps.AuditConfig",
    "apps.teams.apps.TeamConfig",
    "apps.skills.apps.SkillConfig",
    "apps.locations.apps.LocationConfig",
    "apps.employment_types.apps.EmploymentTypeConfig",
    "apps.roles.apps.RoleConfig",
    "apps.financial_years.apps.FinancialYearConfig",
    "apps.holidays.apps.HolidayConfig",
    "apps.leaves.apps.LeaveConfig",
    "apps.sprints.apps.SprintConfig",
    "apps.projects.apps.ProjectConfig",
    "apps.dashboard.apps.DashboardConfig",
    "apps.business_units.apps.BusinessUnitConfig",
    "apps.products.apps.ProductConfig",
    "apps.tags.apps.TagConfig",
    "apps.contacts.apps.ContactConfig",
    "apps.comments.apps.CommentsConfig",
    "apps.recharges.apps.RechargeConfig",
    "apps.how_to.apps.HowToConfig",
    "apps.notifications.apps.NotificationsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.setup.middleware.SetupMiddleware",
    "apps.auth.middleware.SessionTimeoutMiddleware",
    "apps.auth.middleware.PasswordPolicyMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.user_permissions",
                "apps.core.context_processors.messages_for_js",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database — see config/database.py for engine selection and connection details.
DATABASES = database.DATABASES


LOGIN_URL = "/login/"

AUTHENTICATION_BACKENDS = [
    "apps.permissions.backends.PermissionCategoryBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# In development (DEBUG=True), Django's runserver serves static files directly
# from STATICFILES_DIRS — no manifest or collectstatic required.
# In production (DEBUG=False), WhiteNoise serves from STATIC_ROOT using a
# manifest for cache-busting; collectstatic must be run before the server starts.
WHITENOISE_AUTOREFRESH = DEBUG
_TESTING = "pytest" in sys.modules

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if _TESTING
            else "whitenoise.storage.CompressedStaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Media files (user uploads, avatars, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGGING = logging.LOGGING

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.auth.authentication.BearerTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Resource Planner API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "DESCRIPTION": (
        "## Resource Planner API\n\n"
        "A comprehensive REST API for managing projects, resources,"
        " teams, and planning workflows.\n\n"
        "### Authentication\n\n"
        "All private endpoints require a **Bearer Token** in the"
        " `Authorization` header:\n\n"
        "```\nAuthorization: Bearer <token>\n```\n\n"
        "Obtain a token via the **Login** endpoint under"
        " **Authentication: Classic**.\n\n"
        "### Pagination\n\n"
        "All list endpoints return a paginated envelope:\n\n"
        "```json\n"
        "{\n"
        '  "success": true,\n'
        '  "data": {\n'
        '    "results": [...],\n'
        '    "pagination": {\n'
        '      "total_count": 100,\n'
        '      "total_pages": 5,\n'
        '      "current_page": 1,\n'
        '      "page_size": 25,\n'
        '      "has_next": true,\n'
        '      "has_previous": false\n'
        "    }\n"
        "  }\n"
        "}\n"
        "```\n\n"
        "### Filtering & Sorting\n\n"
        "Use `search`, `sort`, `order_by` (ASC/DESC), `page`,"
        " and `page_size` query parameters on list endpoints."
    ),
    "TAGS": [
        # ── Authentication & Access ──
        {
            "name": "Authentication: Classic",
            "description": "Login, logout, and password reset flows.",
        },
        {
            "name": "Authentication: OAuth",
            "description": "OAuth2 provider connection and callback handling.",
        },
        {
            "name": "Authentication: SAML",
            "description": "SAML SSO configuration and IdP-initiated flows.",
        },
        # ── Platform ──
        {
            "name": "Setup",
            "description": "Application setup wizard — run once on installation.",
        },
        {
            "name": "Metadata: Users",
            "description": "App metadata available to authenticated users.",
        },
        {
            "name": "Permissions",
            "description": "System-wide permission definitions and queries.",
        },
        {
            "name": "Permissions: Users",
            "description": "Permission assignments and overrides per user.",
        },
        {
            "name": "Permissions: Groups",
            "description": "Permission assignments and overrides per group.",
        },
        # ── People & Organisation ──
        {
            "name": "Users",
            "description": "User account management, profiles, and admin.",
        },
        {
            "name": "Members",
            "description": "Team member assignments, skills, and availability.",
        },
        {
            "name": "Groups",
            "description": "User groups and group-level permission management.",
        },
        {
            "name": "Teams",
            "description": "Team management, members, and configuration.",
        },
        # ── Master Data ──
        {
            "name": "Skills",
            "description": "Resource skills and competency catalog.",
        },
        {
            "name": "Locations",
            "description": "Office locations and site configuration.",
        },
        {
            "name": "Employment Types",
            "description": "Employment type definitions (full-time, contractor…).",
        },
        {
            "name": "Roles",
            "description": "Job roles and functional role catalog.",
        },
        {
            "name": "Business Units",
            "description": "Business unit hierarchy and structure.",
        },
        {
            "name": "Tags",
            "description": "Free-form labels for planning entities.",
        },
        # ── Planning ──
        {
            "name": "Financial Years",
            "description": "Financial year and planning period configuration.",
        },
        {
            "name": "Holidays",
            "description": "Holiday calendars by location.",
        },
        {
            "name": "Leaves",
            "description": "Leave types and entitlement configuration.",
        },
        {
            "name": "Sprints",
            "description": "Sprint lifecycle management and capacity planning.",
        },
        # ── Projects & Programmes ──
        {
            "name": "Programmes",
            "description": "Programme management — groups of related projects.",
        },
        {
            "name": "Projects",
            "description": "Project tracking, governance, and resource allocation.",
        },
        {
            "name": "Projects: Budgets",
            "description": "Budget management for projects.",
        },
        {
            "name": "Projects: Estimates",
            "description": "Effort and cost estimates for project work.",
        },
        {
            "name": "Projects: Labels",
            "description": "Label management for projects.",
        },
        {
            "name": "Projects: Statuses",
            "description": "Project status definitions and workflow configuration.",
        },
        {
            "name": "Projects: Tags",
            "description": "Tag assignments on projects.",
        },
        {
            "name": "Projects: Types",
            "description": "Project type definitions and category configuration.",
        },
    ],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": False,
        "docExpansion": "list",
        "filter": True,
        "defaultModelsExpandDepth": -1,
        "defaultModelExpandDepth": 3,
        "tryItOutEnabled": False,
        "displayRequestDuration": True,
    },
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": True,
    "SECURITY": [
        {
            "BearerAuth": [],
        }
    ],
}

SILENCED_SYSTEM_CHECKS = [
    "security.W004",
    "security.W008",
    "security.W009",
    "security.W012",
    "security.W016",
    "security.W018",
]
