# Generated by Django 6.0.5 on 2026-07-04 20:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0005_alter_assignment_created_by_and_more"),
        ("wins", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyWin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("phase_1_open", "Phase 1 Open"),
                            ("phase_1_closed", "Phase 1 Closed"),
                            ("phase_2_open", "Phase 2 Open"),
                            ("phase_2_closed", "Phase 2 Closed"),
                            ("wins_declared", "Wins Declared"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("phase1_deadline", models.DateTimeField(blank=True, null=True)),
                ("phase2_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wins",
                    models.ManyToManyField(
                        blank=True, related_name="monthly_wins", to="wins.win"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_monthlywin", "Can manage Monthly Win phases and surveys")
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyWinSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "phase",
                    models.CharField(
                        choices=[("phase_1", "Phase 1"), ("phase_2", "Phase 2")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("overridden", "Overridden"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_count", models.PositiveIntegerField(default=0)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "monthly_win",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="wins.monthlywin",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_win_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True, related_name="monthly_win_surveys", to="teams.team"
                    ),
                ),
            ],
            options={
                "ordering": ["recipient__email"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyWinResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("operational_excellence", "Operational Excellence"),
                        ],
                        max_length=25,
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("vote_count", models.PositiveIntegerField(default=0)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_results",
                        to="wins.winentry",
                    ),
                ),
                (
                    "monthly_win",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="wins.monthlywin",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("monthly_win", "category", "rank"),
                        name="wins_monthlywinresult_monthly_win_category_rank_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyWinsRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_wins_recipients",
                        to="teams.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_wins_recipient_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["team__name", "user__email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "user"),
                        name="wins_monthlywinsrecipient_team_user_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonthlyWinSurveyNomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("operational_excellence", "Operational Excellence"),
                        ],
                        max_length=25,
                    ),
                ),
                ("is_dismissed", models.BooleanField(default=False)),
                ("dismissed_reason", models.CharField(blank=True, max_length=300)),
                ("nominated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="wins.winentry",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="wins.monthlywinsurvey",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "entry__team__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("survey", "entry", "category"),
                        name="wins_monthlywinsurveynomination_survey_entry_category_uniq",
                    )
                ],
            },
        ),
    ]
