# Generated by Django 6.0.5 on 2026-06-13 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_add_project_follower"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveIntegerField(db_index=True)),
                (
                    "estimate_link",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEWED", "Reviewed"),
                            ("SHARED", "Shared"),
                            ("APPROVED", "Approved"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "estimate_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "contingency_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("day_rate", models.PositiveIntegerField(default=0)),
                (
                    "approval_email_sent",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates",
                        to="projects.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reviewed_project_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_project_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["project", "-version"],
                "permissions": [
                    ("export_projectestimate", "Can export project estimates")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectEstimateStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("APPROVED", "Approved"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEWED", "Reviewed"),
                            ("SHARED", "Shared"),
                            ("APPROVED", "Approved"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEWED", "Reviewed"),
                            ("SHARED", "Shared"),
                            ("APPROVED", "Approved"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("changed_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_estimate_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="projects.projectestimate",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_on"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectestimate",
            constraint=models.UniqueConstraint(
                fields=("project", "version"),
                name="projects_projectestimate_project_version_uniq",
            ),
        ),
    ]
