# Generated by Django 6.0.5 on 2026-06-14 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_add_project_budget_and_status_history"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="efforts_issues",
            new_name="efforts_issued",
        ),
    ]
