# Generated by Django 6.0.5 on 2026-05-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saml", "0002_alter_saml_sp_entity_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="saml",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
