# Generated by Django 6.0.5 on 2026-06-20 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recharges", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projecttypemapping",
            options={
                "ordering": ["project_type__name"],
                "permissions": [
                    ("import_projecttypemapping", "Can import project type mappings"),
                    ("export_projecttypemapping", "Can export project type mappings"),
                ],
            },
        ),
    ]
