# Generated by Django 6.0.5 on 2026-06-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0023_alter_projectactuals_created_at_and_more"),
        ("recharges", "0007_rechargedetail_recharge_recharge_type"),
        ("sprints", "0022_alter_sprintdataimport_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recharge",
            name="recharges_recharge_sprint_type_programme_project_recha_a25ae731",
        ),
        migrations.AddConstraint(
            model_name="recharge",
            constraint=models.UniqueConstraint(
                fields=("sprint", "type", "programme", "project", "recharge_type"),
                name="recharges_recharge_sprint_type_programme_project_r_a25ae731",
            ),
        ),
    ]
