# Generated by Django 6.0.5 on 2026-06-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recharges", "0011_rechargeemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rechargeemail",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="rechargeemail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
