# Generated by Django 6.0.5 on 2026-05-21 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("description", models.CharField(blank=True)),
                (
                    "config_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_config_code",
                                message=(
                                    "Code must start with an uppercase letter"
                                    " and contain only uppercase letters, digits,"
                                    " and underscores (e.g. DEFAULT_HOLIDAYS)."
                                ),
                                regex="^[A-Z][A-Z0-9_]*$",
                            )
                        ],
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("value", models.CharField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                        ],
                        default="string",
                        max_length=10,
                    ),
                ),
                ("is_secret", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "module",
                    models.CharField(
                        choices=[("setup", "Setup"), ("general", "General")],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["config_code"],
            },
        ),
    ]
