# Generated by Django 6.0.5 on 2026-05-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="module",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("general", "General"),
                    ("auth", "Authentication"),
                    ("infra", "Infrastructure"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
