# Generated by Django 6.0.5 on 2026-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0003_alter_configuration_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="module",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("general", "General"),
                    ("auth", "Authentication"),
                    ("infra", "Infrastructure"),
                    ("email", "Email"),
                    ("holidays", "Holidays"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
