# Generated by Django 6.0.5 on 2026-07-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurations", "0009_alter_configuration_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="module",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("general", "General"),
                    ("auth", "Authentication"),
                    ("infra", "Infrastructure"),
                    ("email", "Email"),
                    ("holidays", "Holidays"),
                    ("financial_year", "Financial Year"),
                    ("sprints", "Sprints"),
                    ("users", "Users"),
                    ("projects", "Projects"),
                    ("ai", "AI"),
                    ("security", "Security"),
                    ("security_password", "Security - Password"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
