# Generated by Django 6.0.5 on 2026-07-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="icon",
            field=models.CharField(blank=True, default="bi-bar-chart", max_length=50),
        ),
    ]
