# Generated by Django 6.0.5 on 2026-05-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
