name: Gitleaks Secret Scan
description: Scan for secrets using Gitleaks

runs:
  using: composite
  steps:
    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
