name: Bandit
description: Run Bandit security scanner

inputs:
  path:
    description: Space-separated path(s) to scan recursively
    required: true

runs:
  using: composite
  steps:
    - name: Bandit
      id: bandit
      shell: bash
      run: bandit -r ${{ inputs.path }} --configfile pyproject.toml -f sarif -o bandit.sarif
      continue-on-error: true

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: bandit.sarif
        category: bandit

    - name: Fail on findings
      shell: bash
      if: steps.bandit.outcome == 'failure'
      run: exit 1
