# Generated by Django 6.0.5 on 2026-07-01 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        ("financial_years", "0002_alter_financialyear_created_by_and_more"),
        ("projects", "0027_onboardingattachment_storage_fields"),
        ("resource_plans", "0002_resource_plan_comment"),
        ("teams", "0005_alter_assignment_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResourcePlan",
            new_name="Plan",
        ),
        migrations.RenameModel(
            old_name="ResourcePlanComment",
            new_name="PlanComment",
        ),
        migrations.RenameModel(
            old_name="ResourcePlanScope",
            new_name="PlanScope",
        ),
        migrations.RenameModel(
            old_name="ResourcePlanVersion",
            new_name="PlanVersion",
        ),
        migrations.RemoveConstraint(
            model_name="plan",
            name="resource_plans_resourceplan_name_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="planversion",
            name="resource_plans_resourceplanversion_plan_version_uniq",
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                fields=("name",), name="resource_plans_plan_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="planversion",
            constraint=models.UniqueConstraint(
                fields=("plan", "version"),
                name="resource_plans_planversion_plan_version_uniq",
            ),
        ),
    ]
