# Generated by Django 6.0.5 on 2026-07-01 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_onboardingattachment_storage_fields"),
        ("resource_plans", "0003_rename_resourceplan_plan_and_more"),
        ("sprints", "0022_alter_sprintdataimport_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanVersionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("estimate", "Estimate"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "basis_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("basis_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "days_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "priority_snapshot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "priority_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "confidence_snapshot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "confidence_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("dates_strict", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "end_sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_plan_versions_ended",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_plan_versions",
                        to="projects.project",
                    ),
                ),
                (
                    "snapshotted_budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_plan_versions",
                        to="projects.projectbudget",
                    ),
                ),
                (
                    "snapshotted_estimate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_plan_versions",
                        to="projects.projectestimate",
                    ),
                ),
                (
                    "start_sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_plan_versions_started",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="resource_plans.planversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "project"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "project"),
                        name="resource_plans_planversionproject_version_project_uniq",
                    )
                ],
            },
        ),
    ]
