# Generated by Django 6.0.5 on 2026-07-02 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_plans", "0005_planversionteam"),
        ("sprints", "0022_alter_sprintdataimport_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("sequence_order", models.PositiveIntegerField(default=1)),
                (
                    "max_days_per_sprint",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ramp_pattern",
                    models.CharField(
                        choices=[
                            ("flat", "Flat"),
                            ("ramp_up", "Ramp Up"),
                            ("ramp_down", "Ramp Down"),
                            ("ramp_up_down", "Ramp Up Down"),
                            ("ramp_up_steady", "Ramp Up Steady"),
                            ("steady_down", "Steady Down"),
                            ("stepped", "Stepped"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="flat",
                        max_length=20,
                    ),
                ),
                ("allow_multiple_engineers", models.BooleanField(default=False)),
                (
                    "split_mode",
                    models.CharField(
                        choices=[
                            ("percent", "Percent"),
                            ("days", "Days"),
                            ("equal", "Equal"),
                            ("auto", "Auto"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("is_split_incomplete", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "days_effort",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "end_sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_phases_ended",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "plan_project_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="resource_plans.planversionteam",
                    ),
                ),
                (
                    "start_sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_phases_started",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["plan_project_team", "sequence_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan_project_team", "name"),
                        name="resource_plans_planphase_plan_project_team_name_uniq",
                    )
                ],
            },
        ),
    ]
