# Generated by Django 6.0.5 on 2026-07-02 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_plans", "0006_planphase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPhaseSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("segment_order", models.PositiveIntegerField()),
                (
                    "segment_type",
                    models.CharField(
                        choices=[("ramp", "Ramp"), ("flat", "Flat")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "start_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("end_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "progression",
                    models.CharField(
                        choices=[
                            ("linear", "Linear"),
                            ("exponential", "Exponential"),
                            ("logarithmic", "Logarithmic"),
                            ("stepped", "Stepped"),
                            ("flat", "Flat"),
                        ],
                        default="linear",
                        max_length=20,
                    ),
                ),
                ("duration", models.PositiveIntegerField()),
                ("step_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="resource_plans.planphase",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["phase", "segment_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("phase", "segment_order"),
                        name="resource_plans_planphasesegment_phase_segment_order_uniq",
                    )
                ],
            },
        ),
    ]
