# Generated by Django 6.0.5 on 2026-07-02 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_plans", "0007_planphasesegment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPhaseDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("start_to_start", "Start to Start"),
                            ("finish_to_start", "Finish to Start"),
                            ("finish_to_finish", "Finish to Finish"),
                            ("start_to_finish", "Start to Finish"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("lag_sprints", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="resource_plans.planphase",
                    ),
                ),
                (
                    "predecessor_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_on",
                        to="resource_plans.planphase",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["phase", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("phase", "predecessor_phase"),
                        name="resource_plans_planphasedependency_phase_predecessor_phase_uniq",
                    )
                ],
            },
        ),
    ]
