# Generated by Django 6.0.5 on 2026-07-03 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_plans", "0010_planassignment"),
        ("sprints", "0022_alter_sprintdataimport_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanBudgetRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("sprint", "Sprint"), ("month", "Month")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("month", models.CharField(blank=True, max_length=7, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_version_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_releases",
                        to="resource_plans.planversionproject",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_budget_releases",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["plan_version_project", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "plan_version_project",
                            "entry_type",
                            "sprint",
                            "month",
                        ),
                        name="resource_plans_planbudgetrelease_plan_version_proj_42a09b51",
                    )
                ],
            },
        ),
    ]
