# Generated by Django 6.0.5 on 2026-07-03 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_plans", "0011_planbudgetrelease"),
        ("sprints", "0022_alter_sprintdataimport_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planphase",
            name="end_sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_phases_ended",
                to="sprints.sprint",
            ),
        ),
        migrations.AlterField(
            model_name="planphase",
            name="max_days_per_sprint",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="planphase",
            name="start_sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_phases_started",
                to="sprints.sprint",
            ),
        ),
    ]
