# Generated by Django 6.0.5 on 2026-07-03 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_plans", "0012_alter_planphase_end_sprint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("validate", "Validate"), ("full", "Full")],
                        db_index=True,
                        default="validate",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                ("include_current_sprint", models.BooleanField(default=False)),
                ("dry_run", models.BooleanField(default=False)),
                ("remove_overrides", models.BooleanField(default=False)),
                (
                    "initiated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_milliseconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("validation_result", models.JSONField(blank=True, default=dict)),
                ("steps_log", models.JSONField(blank=True, default=list)),
                ("error_log", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engine_jobs",
                        to="resource_plans.plan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engine_jobs",
                        to="resource_plans.planversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="EngineJobStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("step_order", models.PositiveIntegerField()),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("validate_configuration", "Validate Configuration"),
                            (
                                "override_placeholder_leaves",
                                "Override Placeholder Leaves",
                            ),
                            (
                                "generate_placeholder_leaves",
                                "Generate Placeholder Leaves",
                            ),
                            ("sync_capacity_snapshot", "Sync Capacity Snapshot"),
                            ("build_dependency_graph", "Build Dependency Graph"),
                            ("compute_allocations", "Compute Allocations"),
                            ("detect_conflicts", "Detect Conflicts"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_milliseconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="resource_plans.enginejob",
                    ),
                ),
            ],
            options={
                "ordering": ["job", "step_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "step_order"),
                        name="resource_plans_enginejobstep_job_step_order_uniq",
                    )
                ],
            },
        ),
    ]
