# Generated by Django 6.0.5 on 2026-07-03 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_onboardingattachment_storage_fields"),
        ("resource_plans", "0013_enginejob_enginejobstep"),
        ("sprints", "0022_alter_sprintdataimport_options"),
        ("teams", "0005_alter_assignment_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engine_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_sets",
                        to="resource_plans.enginejob",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_sets",
                        to="resource_plans.planversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("capacity_exceeded", "Capacity Exceeded"),
                            ("competing_priority", "Competing Priority"),
                            ("timeline_breach", "Timeline Breach"),
                            ("budget_exceeded", "Budget Exceeded"),
                            ("dependency_violated", "Dependency Violated"),
                            ("unresolvable_gap", "Unresolvable Gap"),
                            ("threshold_breach", "Threshold Breach"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Error"), (1, "Warning"), (2, "Info")],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("engine_data", models.JSONField(blank=True, default=dict)),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("deprioritised", "Deprioritised"),
                            ("timeline_shifted", "Timeline Shifted"),
                            ("engineer_swapped", "Engineer Swapped"),
                            ("team_changed", "Team Changed"),
                            ("manpower_raised", "Manpower Raised"),
                            ("rebalanced", "Rebalanced"),
                            ("dismissed", "Dismissed"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "affected_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_plan_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "affected_phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflicts",
                        to="resource_plans.planphase",
                    ),
                ),
                (
                    "affected_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_plan_conflicts",
                        to="projects.project",
                    ),
                ),
                (
                    "affected_sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_plan_conflicts",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "affected_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_plan_conflicts",
                        to="teams.team",
                    ),
                ),
                (
                    "allocation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="resource_plans.allocationset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engine_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts",
                        to="resource_plans.enginejob",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManpowerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("sprints_needed", models.PositiveIntegerField()),
                (
                    "days_needed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("hiring", "Hiring"),
                            ("rebalanced", "Rebalanced"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allocation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manpower_requests",
                        to="resource_plans.allocationset",
                    ),
                ),
                (
                    "conflict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manpower_requests",
                        to="resource_plans.conflict",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manpower_requests",
                        to="resource_plans.planphase",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manpower_requests",
                        to="teams.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EngineerHirePlaceholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("sequence_number", models.PositiveIntegerField()),
                ("display_name", models.CharField(max_length=255)),
                (
                    "capacity_days_per_sprint",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("replaced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engine_suggested_sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engineer_hire_placeholders_suggested",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "onboard_sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engineer_hire_placeholders_onboarding",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engineer_hire_placeholders_replaced",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engineer_hire_placeholders",
                        to="teams.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineer_hire_placeholders",
                        to="resource_plans.planversion",
                    ),
                ),
                (
                    "manpower_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engineer_hire_placeholders",
                        to="resource_plans.manpowerrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="MemberCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "working_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "holiday_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "leave_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "placeholder_leave_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_capacity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_capacities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_capacities",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_capacities",
                        to="resource_plans.planversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "member", "sprint"],
            },
        ),
        migrations.CreateModel(
            name="PlaceholderEngineer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("slot_number", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("engineer", "Engineer"),
                            ("architect", "Architect"),
                            ("adhoc", "Adhoc"),
                            ("interim", "Interim"),
                        ],
                        db_index=True,
                        default="engineer",
                        max_length=20,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placeholder_engineers",
                        to="resource_plans.planphase",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placeholder_engineers",
                        to="teams.team",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placeholder_engineers",
                        to="resource_plans.planversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "team", "slot_number"],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("engineer", "Engineer"),
                            ("architect", "Architect"),
                            ("adhoc", "Adhoc"),
                            ("interim", "Interim"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("includes_in_budget", models.BooleanField(default=True)),
                (
                    "engine_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "override_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("override_notes", models.TextField(blank=True, default="")),
                ("overridden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations",
                        to="resource_plans.planassignment",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_plan_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="resource_plans.planphase",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_plan_allocations",
                        to="projects.programme",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_plan_allocations",
                        to="projects.project",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_plan_allocations",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_plan_allocations",
                        to="teams.team",
                    ),
                ),
                (
                    "allocation_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="resource_plans.allocationset",
                    ),
                ),
                (
                    "placeholder_engineer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="resource_plans.placeholderengineer",
                    ),
                ),
            ],
            options={
                "ordering": ["allocation_set", "sprint"],
            },
        ),
        migrations.CreateModel(
            name="PlaceholderLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_auto", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placeholder_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placeholder_leaves",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placeholder_leaves",
                        to="resource_plans.planversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "member", "sprint"],
            },
        ),
        migrations.CreateModel(
            name="EngineerHirePlaceholderAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_engine_generated", models.BooleanField(default=True)),
                (
                    "override_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("override_notes", models.TextField(blank=True, default="")),
                (
                    "placeholder_engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="resource_plans.engineerhireplaceholder",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engineer_hire_placeholder_absences",
                        to="sprints.sprint",
                    ),
                ),
            ],
            options={
                "ordering": ["placeholder_engineer", "sprint"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("placeholder_engineer", "sprint"),
                        name="resource_plans_engineerhireplaceholderabsence_plac_12ebe1a4",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="engineerhireplaceholder",
            constraint=models.UniqueConstraint(
                fields=("version", "sequence_number"),
                name="resource_plans_engineerhireplaceholder_version_seq_8f90ab59",
            ),
        ),
        migrations.AddConstraint(
            model_name="membercapacity",
            constraint=models.UniqueConstraint(
                fields=("version", "member", "sprint"),
                name="resource_plans_membercapacity_version_member_sprint_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="placeholderengineer",
            constraint=models.UniqueConstraint(
                fields=("version", "team", "slot_number"),
                name="resource_plans_placeholderengineer_version_team_sl_2f70d39b",
            ),
        ),
        migrations.AddConstraint(
            model_name="placeholderleave",
            constraint=models.UniqueConstraint(
                fields=("version", "member", "sprint"),
                name="resource_plans_placeholderleave_version_member_sprint_uniq",
            ),
        ),
    ]
