# Generated by Django 6.0.5 on 2026-07-03 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_onboardingattachment_storage_fields"),
        ("resource_plans", "0014_allocationset_conflict_manpowerrequest_and_more"),
        ("sprints", "0022_alter_sprintdataimport_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planphasepause",
            name="is_beyond_fy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planversionproject",
            name="is_over_threshold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planversionproject",
            name="is_percent_incomplete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planversionproject",
            name="is_team_budget_mismatch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planversionproject",
            name="is_under_threshold",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="resource_plans.planphase",
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resource_plan_allocations",
                to="projects.programme",
            ),
        ),
        migrations.AlterField(
            model_name="conflict",
            name="engine_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicts",
                to="resource_plans.enginejob",
            ),
        ),
        migrations.AlterField(
            model_name="engineerhireplaceholder",
            name="onboard_sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="engineer_hire_placeholders_onboarding",
                to="sprints.sprint",
            ),
        ),
        migrations.AlterField(
            model_name="manpowerrequest",
            name="conflict",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manpower_requests",
                to="resource_plans.conflict",
            ),
        ),
        migrations.AlterField(
            model_name="manpowerrequest",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manpower_requests",
                to="resource_plans.planphase",
            ),
        ),
        migrations.AddConstraint(
            model_name="planassignment",
            constraint=models.UniqueConstraint(
                fields=("phase", "member", "assignment_type"),
                name="resource_plans_planassignment_phase_member_assignment_type_uniq",
            ),
        ),
    ]
