# Generated by Django 6.0.5 on 2026-07-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_plans", "0015_planphasepause_is_beyond_fy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enginejob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enginejobstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
