# Generated by Django 6.0.5 on 2026-07-04 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_plans", "0016_alter_enginejob_status_alter_enginejobstep_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("label", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_allocation_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_members", models.PositiveIntegerField(default=0)),
                ("total_projects", models.PositiveIntegerField(default=0)),
                ("total_sprints", models.PositiveIntegerField(default=0)),
                (
                    "initiated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_milliseconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error_log", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="resource_plans.plan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="resource_plans.planversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sprint_number", models.PositiveIntegerField(db_index=True)),
                ("sprint_name", models.CharField(max_length=100)),
                ("member_name", models.CharField(db_index=True, max_length=255)),
                ("team_name", models.CharField(max_length=100)),
                ("project_name", models.CharField(max_length=255)),
                (
                    "programme_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "phase_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("assignment_type", models.CharField(max_length=20)),
                ("includes_in_budget", models.BooleanField(default=True)),
                (
                    "days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_override", models.BooleanField(default=False)),
                ("is_placeholder", models.BooleanField(default=False)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="resource_plans.snapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["sprint_number", "member_name"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sprint_number", models.PositiveIntegerField(db_index=True)),
                ("sprint_name", models.CharField(max_length=100)),
                ("member_name", models.CharField(db_index=True, max_length=255)),
                ("team_name", models.CharField(max_length=100)),
                (
                    "working_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "holiday_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "leave_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "placeholder_leave_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_capacity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacities",
                        to="resource_plans.snapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["sprint_number", "member_name"],
            },
        ),
    ]
