# Generated by Django 6.0.5 on 2026-07-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_plans", "0017_snapshot_snapshotallocation_snapshotcapacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshotallocation",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("engineer", "Engineer"),
                    ("architect", "Architect"),
                    ("adhoc", "Adhoc"),
                    ("interim", "Interim"),
                ],
                max_length=20,
            ),
        ),
    ]
