# Generated by Django 6.0.5 on 2026-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_useravatar_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_holidays",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="joined_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="leaving_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
