# Generated by Django 6.0.5 on 2026-06-13 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_groupprofile_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupprofile",
            options={
                "ordering": ["group"],
                "permissions": [
                    ("view_group", "Can view groups"),
                    ("add_group", "Can add groups"),
                    ("change_group", "Can change groups"),
                    ("delete_group", "Can delete groups"),
                    ("import_group", "Can import groups"),
                    ("export_group", "Can export groups"),
                ],
            },
        ),
    ]
