name: Markdown Lint

on:
  pull_request:
    paths:
      - "docs/**"
      - "*.md"

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v16
