name: Packages CI

on:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Secret Scan (Gitleaks)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/gitleaks

  lint:
    name: Lint (${{ matrix.package }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: &packages
          - aicore
          - awscore
          - emailcore
          - exportcore
          - otpcore
          - pycore
          - storagecore

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-python

      - uses: ./.github/actions/install-python-deps

      - uses: ./.github/actions/install-packages
        with:
          package: ${{ matrix.package }}

      - uses: ./.github/actions/ruff
        with:
          path: packages/${{ matrix.package }}

      - uses: ./.github/actions/mypy
        with:
          path: packages/${{ matrix.package }}

      - uses: ./.github/actions/bandit
        with:
          path: packages/${{ matrix.package }}

      - uses: ./.github/actions/pip-audit

  tests:
    name: Tests (${{ matrix.package }})
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: *packages

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-python

      - uses: ./.github/actions/install-python-deps

      - uses: ./.github/actions/install-packages
        with:
          package: ${{ matrix.package }}

      - uses: ./.github/actions/pytest
        with:
          path: packages/${{ matrix.package }}/tests/
          name: ${{ matrix.package }}
          extra-args: "-p no:django --import-mode=importlib"
          artifact-name: packages-test-report-${{ matrix.package }}

      - uses: ./.github/actions/build-validate
        with:
          package: ${{ matrix.package }}
