name: Web CI

on:
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/**"
      - ".github/workflows/web-ci.yml"

permissions:
  contents: read

jobs:
  gitleaks:
    name: Secret Scan (Gitleaks)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: ./.github/actions/gitleaks

  lint:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-python

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/install-python-deps

      - uses: ./.github/actions/install-node-deps

      - uses: ./.github/actions/build-frontend-assets

      - uses: ./.github/actions/ruff
        with:
          path: "."

      - uses: ./.github/actions/mypy
        with:
          path: apps/web

      - uses: ./.github/actions/bandit
        with:
          path: "apps/web packages"

      - uses: ./.github/actions/pip-audit

      - uses: ./.github/actions/django-check

      - uses: ./.github/actions/openapi-validation

  unit-tests:
    name: Unit Tests (${{ matrix.app }})
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: &apps
          - audit
          - auth
          - business_units
          - configurations
          - employment_types
          - financial_years
          - holidays
          - leaves
          - locations
          - meta
          - oauth
          - permissions
          - projects
          - roles
          - saml
          - setup
          - skills
          - sprints
          - tags
          - teams
          - users

    steps:
      - uses: ./.github/actions/setup-python

      - uses: ./.github/actions/install-python-deps

      - uses: ./.github/actions/unit-test
        with:
          path: apps/web/apps/${{ matrix.app }}/tests/
          name: ${{ matrix.app }}
          artifact-name: unit-test-report-${{ matrix.app }}

  integration-tests:
    name: Integration Tests (${{ matrix.app }})
    needs: [unit-tests]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: *apps

    steps:
      - uses: ./.github/actions/setup-python

      - uses: ./.github/actions/install-python-deps

      - uses: ./.github/actions/integration-test
        with:
          path: apps/web/apps/${{ matrix.app }}/tests/
          name: ${{ matrix.app }}
          artifact-name: test-report-${{ matrix.app }}
